version: '3.4'
services:
  web:
    image: node:20.4.0-alpine
    container_name: reactive-form
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - .:/app
    tty: true
